let mimeTypes = {
	'audio/aac': '{JS:L:AUDIO_FILE} AAC',
	'audio/midi': '{JS:L:AUDIO_FILE} MIDI',
	'audio/ogg': '{JS:L:AUDIO_FILE} OGG',
	'audio/x-wav': '{JS:L:AUDIO_FILE} WAV',
	'audio/webm': '{JS:L:AUDIO_FILE} WEBM',
	'audio/3gpp2': '{JS:L:AUDIO_FILE} 3GPP2',
	'audio/3gpp': '{JS:L:AUDIO_FILE} 3GPP',
	'audio/mpeg': '{JS:L:AUDIO_FILE} MPEG',

	'application/x-abiword': '{JS:L:ABIWORD}',
	'application/vnd.amazon.ebook': '{JS:L:KINDLE}',
	'application/octet-stream': '{JS:L:BINARY_FILE}',
	'application/x-bzip': '{JS:L:BZIP}',
	'application/x-bzip2': '{JS:L:BZIP2}',
	'application/x-csh': '{JS:L:X_CSH}',
	'application/msword': '{JS:L:MSWORD}',
	'application/vnd.openxmlformats-officedocument.wordprocessingml.document': '{JS:L:WORD_OPENXML}',
	'application/vnd.ms-fontobject': '{JS:L:MS_FONTOBJECT}',
	'application/epub+zip': '{JS:L:EPUB}',
	'application/java-archive': '{JS:L:JAR}',
	'application/javascript': '{JS:L:JAVASCRIPT}',
	'application/json': '{JS:L:JSON}',
	'application/vnd.apple.installer+xml': '{JS:L:APPLE_INSTALLER}',
	'application/vnd.oasis.opendocument.presentation': '{JS:L:OD_PRES}',
	'application/vnd.oasis.opendocument.spreadsheet': '{JS:L:OD_SHEET}',
	'application/vnd.oasis.opendocument.text': '{JS:L:OD_TEXT}',
	'application/ogg': '{JS:L:OGG}',
	'application/pdf': '{JS:L:PDF}',
	'application/vnd.ms-powerpoint': '{JS:L:powerpoint}',
	'application/vnd.openxmlformats-officedocument.presentationml.presentation': '{JS:L:POWERPOINT_OPENXML}',
	'application/x-rar-compressed': '{JS:L:RAR}',
	'application/rtf': '{JS:L:RTF}',
	'application/x-sh': '{JS:L:SHELL}',
	'application/x-shockwave-flash': '{JS:L:FLASH}',
	'application/x-tar': '{JS:L:TAR}',
	'application/typescript': '{JS:L:TYPESCRIPT}',
	'application/vnd.visio': '{JS:L:VISIO}',
	'application/xhtml+xml': '{JS:L:XHTML}',
	'application/vnd.ms-excel': '{JS:L:EXCEL}',
	'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet': '{JS:L:EXCEL_OPENXML}',
	'application/xml': '{JS:L:XML}',
	'application/vnd.mozilla.xul+xml': '{JS:L:XUL}',
	'application/zip': '{JS:L:ZIP}',
	'application/x-7z-compressed': '{JS:L:7ZIP}',

	'font/otf': '{JS:L:OTF}',
	'font/ttf': '{JS:L:TTF}',
	'font/woff': '{JS:L:WOFF}',
	'font/woff2': '{JS:L:WOFF2}',

	'video/x-msvideo': '{JS:L:MSVIDEO}',
	'video/mpeg': '{JS:L:MPEG}',
	'video/ogg': '{JS:L:OGG_VIDEO}',
	'video/webm': '{JS:L:WEBM}',
	'video/3gpp': '{JS:L:3GPP_VIDEO}',
	'video/3gpp2': '{JS:L:3GPP2_VIDEO}',

	'image/bmp': '{JS:L:BMP}',
	'image/gif': '{JS:L:GIF}',
	'image/x-icon': '{JS:L:XICON}',
	'image/jpeg': '{JS:L:JPEG}',
	'image/png': '{JS:L:PNG}',
	'image/svg+xml': '{JS:L:SVG}',
	'image/tiff': '{JS:L:TIFF}',
	'image/webp': '{JS:L:WEBP}',

	'text/css': '{JS:L:CSS}',
	'text/csv': '{JS:L:CSV}',
	'text/html': '{JS:L:HTML}',
	'text/calendar': '{JS:L:ICALENDAR}',
	'text/plain': '{JS:L:TEXT_PLAIN}'
};